version: '3'
services:
  nodeproject:
    build: .
    env_file: .env
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
