version: '3'
services:
  discordbot:
    container_name: discordbot
    build: .
    volumes:
      - ./config.json:/home/runner/config.json:rw
    healthcheck:
      test: curl --fail localhost || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 30s
