version: '3'
services:
  nodeproject:
    build: .
    env_file: .env
    healthcheck:
      test: curl --fail localhost || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 30s
